stages:
  - test
  - publish

test-job:
  stage: test
  tags:
    - moreillon
  script:
    - bun install
    - bun test

publish-job:
  stage: publish
  tags:
    - moreillon
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - npm publish
