stages:
  - test
  - publish

test-job:
  stage: test
  only:
    - tags
  tags:
    - dind
  image: oven/bun:1
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  script:
    - bun install
    - bun test --coverage

publish-job:
  stage: publish
  image: oven/bun:1
  only:
    - tags
  tags:
    - moreillon
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - bun install
    - bun run build
    - bun publish
